// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkAPI.DataContext;

namespace Park.Infrastructure.Migrations
{
    [DbContext(typeof(ParkDbContext))]
    [Migration("20210305125407_myFirstMigration")]
    partial class myFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Parks.Core.Park", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Established")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Type");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f9168c5e-ceb2-4faa-b6bf-329bf39fa1e4"),
                            Created = new DateTime(2021, 3, 5, 13, 54, 6, 714, DateTimeKind.Local).AddTicks(3336),
                            Established = new DateTime(2021, 3, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "MyName",
                            State = "New"
                        },
                        new
                        {
                            Id = new Guid("a0dcdcee-cd26-4246-847a-ed633a86772a"),
                            Created = new DateTime(1990, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Established = new DateTime(1, 4, 27, 21, 33, 21, 10, DateTimeKind.Unspecified).AddTicks(1111),
                            Name = "Alabama",
                            State = "my Dear FrodoBack and Again"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
