// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkAPI.DataContext;

namespace Park.Infrastructure.Migrations
{
    [DbContext(typeof(ParkDbContext))]
    [Migration("20210421094805_adding new object")]
    partial class addingnewobject
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Parks.Cores.Parky", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Established")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f9168c5e-ceb2-4faa-b6bf-329bf39fa1e4"),
                            Created = new DateTime(2021, 4, 21, 11, 48, 4, 622, DateTimeKind.Local).AddTicks(1887),
                            Established = new DateTime(2021, 4, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Name = "",
                            State = "New"
                        },
                        new
                        {
                            Id = new Guid("2849cfba-9407-4faf-bc85-e5a30b7e15d9"),
                            Created = new DateTime(2021, 4, 21, 11, 48, 4, 625, DateTimeKind.Local).AddTicks(8230),
                            Established = new DateTime(1990, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = true,
                            Name = "Kapiniak",
                            State = "MazovianVoivodeship"
                        },
                        new
                        {
                            Id = new Guid("e8ed2471-726f-4ba9-b9df-8b4edaf8c9f1"),
                            Created = new DateTime(2021, 4, 21, 9, 48, 4, 627, DateTimeKind.Utc).AddTicks(3152),
                            Established = new DateTime(1990, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Bieszczady",
                            State = "Podkarpackie Voivodeship"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
