// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkAPI.DataContext;

namespace Park.Infrastructure.Migrations
{
    [DbContext(typeof(ParkDbContext))]
    [Migration("20210307142328_mySecondmigration")]
    partial class mySecondmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Parks.Cores.Parky", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Established")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f9168c5e-ceb2-4faa-b6bf-329bf39fa1e4"),
                            Created = new DateTime(2021, 3, 7, 15, 23, 27, 753, DateTimeKind.Local).AddTicks(7600),
                            Established = new DateTime(2021, 3, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Name = "MyName",
                            State = "New"
                        },
                        new
                        {
                            Id = new Guid("10f28194-2993-4ae1-b8d8-87e8106320a0"),
                            Created = new DateTime(1990, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Established = new DateTime(1, 4, 27, 21, 33, 21, 10, DateTimeKind.Unspecified).AddTicks(1111),
                            IsDeleted = true,
                            Name = "Alabama",
                            State = "my Dear Frodo Back and Again"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
